require 'shellwords'

task default: %i[node]

task node: ['node:tests']

namespace :node do
  task tests: %i[test_express]

  task :test_express do
    express_tests_file = File.join(__dir__, 'tc_express.rb')
    ruby Shellwords.escape(express_tests_file)
  end
end
