require 'shellwords'

task default: %i[express]

task express: ['express:tests']

namespace :express do
  task tests: [:test_express]

  task :test_express do
    express_tests_file = File.join(__dir__, 'tc_express.rb')
    ruby Shellwords.escape(express_tests_file)
  end
end
